name: holgerkiewel
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfccd'
    - '#11004c'
    - '#ccb291'
    - '#9e887e'
    - '#825f67'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
